name: Code Coverage (PHP)

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'
  workflow_dispatch:
    inputs:
      custom_username:
        description: 'Enter custom username (default is "default-user")'
        required: false
        default: 'default-user'
      project_id:
        description: 'Enter project ID (default is "default-project")'
        required: false
        default: 'default-project'

jobs:
  coverage:
    name: Run PHPUnit and Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Verify Composer and Install Dependencies
      run: |
        # Install Composer
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

        # Check if composer.json exists
        if [ ! -f composer.json ]; then
          echo "composer.json not found. Creating a default one..."
          cat <<EOL > composer.json
          {
            "require-dev": {
              "phpunit/phpunit": "^9.0"
            }
          }
          EOL
        fi

        # Install dependencies
        composer install

    - name: Run PHPUnit and Generate Coverage Report
      run: |
        mkdir -p coverage
        ./vendor/bin/phpunit --coverage-html coverage \
          --coverage-clover coverage/clover.xml \
          tests || true

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: php-coverage-report
        path: coverage/

    - name: Notify External API
      run: |
        API_URL="https://dolphin-app-uzion.ondigitalocean.app/api/setQuality?clientpublic=baef7468287a44d8ac3634026d9fb8d1&clientsecret=181a2f3171117c1bd164c88b1171c1b83114fc1712121b12"
        USER_ID="${{ github.event.inputs.custom_username || 'default-user' }}"
        PROJECT_ID="${{ github.event.inputs.project_id || 'default-project' }}"
        LAST_REQUEST_TIME="$(date +%s)000"

        COVERAGE=$(xmllint --xpath "string(/coverage/project/metrics/@percent)" coverage/clover.xml || echo "0")
        curl -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -d "{
            \"userid\": \"$USER_ID\",
            \"projectid\": \"$PROJECT_ID\",
            \"recordtime\": \"$LAST_REQUEST_TIME\",
            \"coverage\": \"$COVERAGE\"
          }" || echo "API notification failed"
